"""Delete volume from Product.

Revision ID: 3d52ec9ec439
Revises: 
Create Date: 2024-04-26 16:30:30.909937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d52ec9ec439'
down_revision = 'a2eb7ce2f84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('volume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.VARCHAR(length=250), nullable=False))

    # ### end Alembic commands ###
