"""Delete title_en from Product

Revision ID: c1da62bd90a0
Revises: ddd1870354cc
Create Date: 2024-03-23 15:27:24.931165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1da62bd90a0'
down_revision = 'ddd1870354cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=250), nullable=False))
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_rus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_rus', sa.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
