"""Create Product model

Revision ID: ddd1870354cc
Revises: 082550e11306
Create Date: 2024-03-23 14:57:58.627191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd1870354cc'
down_revision = '082550e11306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=250), nullable=True),
    sa.Column('title_rus', sa.String(length=250), nullable=False),
    sa.Column('volume', sa.String(length=250), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=250), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check_positive_amount'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
